# -------------------------------------------------
# Informações básicas do site
# -------------------------------------------------
title: "Seção de Engenharia Cartográfica – IME"      # 👉 Nome que aparece na aba do navegador
description: >-
  Repositório de projetos acadêmicos e de pesquisa da
  Seção de Engenharia Cartográfica do Instituto Militar de Engenharia.
url: "https://engenharia-cartografica-ime.github.io"  # 👉 NÃO coloque / no final
baseurl: ""                                          # raiz (deixe vazio porque o repositório segue o padrão org.github.io)
email: "se6@ime.eb.mil.br"                   # 👉 E‑mail de contato (opcional)

# -------------------------------------------------
# Tema e aparência
# -------------------------------------------------
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: default        # skins: default, air, dark, mint, etc.
search: true                          # ativa a busca interna
timezone: America/Sao_Paulo

# -------------------------------------------------
# Paginação & permalinks
# -------------------------------------------------
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/

# -------------------------------------------------
# Pastas incluídas
# -------------------------------------------------
include:
  - _pages          # onde ficarão suas páginas estáticas

# -------------------------------------------------
# Plugins nativos do Minimal Mistakes
# -------------------------------------------------
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# -------------------------------------------------
# Dados do(a) autor(a) principal (pode deixar genérico)
# -------------------------------------------------
author:
  name   : "Equipe EC‑IME"
  avatar : "/assets/images/bio-photo.jpg"   # 👉 Substitua pelo caminho da sua foto ou logo
  bio    : "Docentes e pesquisadores da Seção de Engenharia Cartográfica."
  links:
    - label: "Site do IME"
      icon: "fas fa-fw fa-university"
      url: "https://www.ime.eb.mil.br"

# -------------------------------------------------
# Links no rodapé (opcionais)
# -------------------------------------------------
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Engenharia-Cartografica-IME"

# -------------------------------------------------
# Defaults (layouts automáticos)
# -------------------------------------------------
defaults:
  # Postagens (se decidir usar blog)
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: false
      related: false
  # Páginas
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false

# -------------------------------------------------
# Arquivos de arquivo (tags e categorias)
# -------------------------------------------------
category_archive:
  type: liquid
  path: /categorias/
tag_archive:
  type: liquid
  path: /tags/
